### ISSUE TITLE
Out of sync branches

### ISSUE THREAD

**Issue by andrewklau** [appuio/letsencrypt#1]
We'd love to collaborate with you on this, I noticed the dev branch isn't in sync with master. Could you let me know which branch to start on and any areas that currently need improvement

**Comment by phil-pona** [comment]
Hi Andrew, glad to hear that, I'm going to clean up the branches with my colleagues and come back to you asap.
regards Thomas

**Comment by phil-pona** [comment]
Hi Andrew, branches are rebased, you can make your contributions on the dev branch, docs will soon be available too.
Thanks

**Comment by dtschan** [comment]
Additional info: `master` branch is the stable version and already functional as documented here: http://docs.appuio.ch/en/latest/letsencrypt-integration.html. On the `dev` branch we develop the next version of Let's Encrypt integration with a better user experience. The `dev` branch currently only shows the routes the logged in user has access to but doesn't yet allow to create and install certificates.
